language: php

sudo: required

php:
- 5.6
- 5.5
- 5.4

compiler:
- gcc

install:
- sudo apt-get update -qq
- sudo apt-get install -qq automake pkg-config build-essential libtool automake autoconf m4 gnulib
- sudo apt-get install -qq check libpcre3 libpcre3-dev libjemalloc-dev libjemalloc1
- sudo apt-get install -qq graphviz-dev graphviz

script:
- phpize
- ./configure --libdir=/usr/lib/x86_64-linux-gnu --enable-debug --with-pcre-dir=/usr
- make
- make test
