language: php

sudo: required

php:
- 5.6
- 5.5

compiler:
- gcc

env:
- NO_INTERACTION=1

install:
- sudo apt-get update -qq
- sudo apt-get install -qq automake pkg-config build-essential libtool automake autoconf m4 gnulib
- sudo apt-get install -qq check libpcre3 libpcre3-dev libjemalloc-dev libjemalloc1
- sudo apt-get install -qq graphviz-dev graphviz
- dpkg -S libpcre3

before_script:
- git submodule init
- git submodule update

script:
- phpize
- ./configure --with-libdir=lib/x86_64-linux-gnu --with-pcre-dir=/usr
- make
- make test
